@startuml

participant user
participant Lambda as Foot1
participant LambdaRequest as Foot2
participant ActivityRunner as Foot5
participant Activity as Foot3
participant Dao as Foot8
database DynamoDB as Foot4

user -> Foot1 : handleRequest()
Foot1 -> Foot2 : builder()
Foot2 --> Foot1 : Request
Foot1 -> Foot5 : runActivity()
Foot5 -> Foot3 : handleRequest()
Foot3 -> Foot8 : performAction()
Foot8 -> Foot4 : performAction()
Foot4 --> Foot8 : result
Foot8 --> Foot3 : result
Foot3 --> Foot5 : builder()
Foot5 --> Foot3 : result
Foot3 --> Foot1 : result

@enduml
